widgets:
  -
    position: left
    type: toc
    index: false
    show_mode: pages_and_posts

  -
    position: left
    type: profile
    author: ''
    author_title: ''
    location: ''
    avatar: ''
    avatar_rounded: true
    gravatar:
    follow_link: https://github.com/gh503
    social_links:
    has_hitokoto: true
    show_mode: default

  -
    position: left
    type: links
    links:
      ROS: 'https://wiki.ros.org/'
      RISC-V: 'https://docs.google.com/document/d/1Qjf6BwMmtqTfzftr3WWf2bRv8Cl4f0qZrWWbr0jCBSU/edit?pli=1'
      玄铁: 'https://www.xrvm.cn/'
      Gitee: 'https://gitee.com/angusrobot'
      Github: 'https://github.com/gh503'
      鹏城实验室: 'https://www.pcl.ac.cn/'
      Pixabay: 'https://pixabay.com/zh/'
      二丫讲梵: 'https://wiki.eryajf.net/nav/#_5-%E4%BC%98%E8%B4%A8%E8%AE%BA%E5%9D%9B'
      Hexo: 'https://hexo.io'
    show_mode: default

  -
    position: right
    type: latest_comment
    show_mode: default

  -
    position: right
    type: recent_posts
    show_mode: default

  -
    position: right
    type: categories
    show_mode: default

  -
    position: right
    type: archives
    show_mode: default

  -
    position: right
    type: tags
    show_mode: default

  -
    position: right
    type: followit
    description: ''
    action_url: ''
    verification_code: ''
    show_mode: default
